#define COLS_NxN // GENERATE_N
#define COLS_HALF_NxN // GENERATE_N-HALF
#define ROWS_NxN // GENERATE_N
#define ROWS_HALF_NxN // GENERATE_N-HALF
#define LOCAL_SIZE_COLS_NxN // GENERATE_LOCAL_SIZE_COLS
#define LOCAL_SIZE_ROWS_NxN // GENERATE_LOCAL_SIZE_ROWS
